import type { Metadata } from "next";
import {
  Geist,
  Geist_Mono,
  Bricolage_Grotesque,
  Outfit,
  Smooch_Sans,
} from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/theme-provider";
import { SidebarProvider, SidebarInset } from "@/components/ui/sidebar";
import { AppSidebar } from "./_components/AppSideBar";
import AppHeader from "./_components/AppHeader";
import UserInitializer from "./_components/UserInitializer";
import { AiSelectedModelProvider } from "@/context/AiSelectedModelProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const bricolageGrotesque = Bricolage_Grotesque({
  variable: "--font-bricolage-grotesque",
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700", "800"],
});

const outfit = Outfit({
  variable: "--font-outfit",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

const smoochSans = Smooch_Sans({
  variable: "--font-smooch-sans",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Arc — Unified Multi‑Model Power",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <body
          className={`${geistSans.variable} ${geistMono.variable} ${bricolageGrotesque.variable} ${outfit.variable} ${smoochSans.variable} antialiased`}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <AiSelectedModelProvider>
              <UserInitializer />
              <SidebarProvider>
                {/* Sidebar */}
                <AppSidebar />

                {/* Main Content */}
                <SidebarInset className="flex min-h-screen flex-col">
                  <AppHeader />
                  <main className="flex-1 px-4 py-2">{children}</main>
                </SidebarInset>
              </SidebarProvider>
            </AiSelectedModelProvider>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}
